# Generated by Django 4.2.6 on 2023-10-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
