# Generated by Django 4.2.6 on 2023-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_vendor_orders_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='priority',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
